### ISSUE TITLE
Change the "master" branch to "main"

### ISSUE THREAD

**Issue by amfred** [Call-for-Code-for-Racial-Justice/Open-Sentencing#12]

**Comment by johnwalicki** [comment]
For Open-Sentencing-* repos that have completely merged branches, its easy to rename master to main
As of 12-08-20, I see that I can rename the top level and aggregrator repos but the UI and Model repos have open branches. Renaming master to main before those PRs are merged will cause some merge confusion.

I'll rename the first two and work with the teams on the others

**Comment by johnwalicki** [comment]
I've renamed master to main.
If you have a local clone, you'll want to rebase.
