### ISSUE TITLE
For help wanted issues, please refer to each sub-repo for a specific of issues

### ISSUE THREAD

**Issue by BchanceIBM** [Call-for-Code-for-Racial-Justice/Open-Sentencing#14]
Each of our repos have a set of issues that we need help with, please refer to these repos here.  Also, please make sure to slack us with questions

Slack:  https://app.slack.com/client/TAHDYCZ6H/C01DJ8J1QP2/thread/C01D7MS0G0K-1603572137.017300

UI:  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/issues
Aggregator:  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues
Open Sentencing Model:  https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Model/issues

**Comment by demilolu** [comment]
@bbbozzz

**Comment by sforsyth089** [comment]
Refreshing!  This helps point new helpers to issues to work on.

**Comment by upkarlidder** [comment]
hmm, looks like stalebot did not keep the issue open even though @sforsyth089 commented on this issue. Going to see why that happened.

Btw, on slack, it says `Issue closed by BchanceIBM` @BchanceIBM. But here it says the bot closed it.
