### ISSUE TITLE
Support alternative methods of authentication

### ISSUE THREAD

**Issue by amfred** [Call-for-Code-for-Racial-Justice/Open-Sentencing#19]
Getting started with IBM ID SSO can be difficult for non-IBMers.
We should add support for other authentication providers.
The UI and Aggregator would need to both support the same providers to get this working end to end.

**Comment by sforsyth089** [comment]
This is not stale.  Yochana is actively working on it.  She will provide an update.

**Comment by yochanah** [comment]
AppId Authentication work is in progress. Troubleshooting issues related to redirect.

**Comment by yochanah** [comment]
UI now supports AppId Authentication

**Comment by upkarlidder** [comment]
This work is done. I added another [PR](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-UI/pull/46) to remove old code. Will close this issue once that is meged.
