### ISSUE TITLE
Sign up here to join weekly community meeting

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing#30]
If you'd like to join our weekly community meeting, comment below and tag @demilolu.

Meeting topics:
- Issue planning
- Updates
- Blockers/Brainstorming.

**Comment by thenickcox** [comment]
@demilolu Hi there. Looks like an interesting project. Hoping to get more context and figure out where my skills might be useful. I'd love to hear more about the weekly meeting. Thanks.

**Comment by upkarlidder** [comment]
@thenickcox wonderful! We have a fun group. Look forward to talking to you!

**Comment by jross1996** [comment]
@demilolu I'd like to join the weekly meeting if possible!

**Comment by demilolu** [comment]
Absolutely!  @jross1996. sorry for the delay @thenickcox! 

Pls join us in Slack if you can: callforcode.org/slack and DM me: Demi Ajayi and I'll get you connected.

Our Open sentencing channel is #racial-justice-open-sentencing

**Comment by sforsyth089** [comment]
We will add to the profile page of our project so it doesn't get lost.
