### ISSUE TITLE
Find a Case or Two / User Stories

### ISSUE THREAD

**Issue by sforsyth089** [Call-for-Code-for-Racial-Justice/Open-Sentencing#52]
### Background on the problem the feature will solve/improved user experience
Stacy will find 1-2 cases and write the user stories. 

Once user stories are in place... we'll have a
1.5 Hour meeting with this team to go through UI/data connection. @wisdomkeeper @siranjujugi @upkarlidder

**Comment by sforsyth089** [comment]
[User Stories Open Sentencing.docx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/7566392/User.Stories.Open.Sentencing.docx)
please review @upkarlidder @siranjujugi @wisdomkeeper and we can meet when everyone is ready.

**Comment by sforsyth089** [comment]
Stacy will break up into 2 main Use Cases / and multiple user stories. "Looking up old fields" as "Use Case" then more ways to do that as stories.  This will help with navigating items in the UI.

**Comment by sforsyth089** [comment]
[User Stories Open Sentencing.docx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/7582603/User.Stories.Open.Sentencing.docx)
Updated per our meeting on Friday.

**Comment by upkarlidder** [comment]
@wisdomkeeper 
- [ ] create usecases.md file
- [ ] add to the main readme as a subsection after the video

**Comment by upkarlidder** [comment]
@wisdomkeeper any updates? Thank you!

**Comment by upkarlidder** [comment]
Task moved to #66. Closing issue.
