### ISSUE TITLE
Move Assests (files etc) to New Assets folder for Non-IBMers

### ISSUE THREAD

**Issue by sforsyth089** [Call-for-Code-for-Racial-Justice/Open-Sentencing#54]

**Comment by joannhh** [comment]
In process -- files still being reviewed for applicability to all.

**Comment by upkarlidder** [comment]
@joannhh reviewing files to determine what can be made public.

The team decided to host on GitHub itself as these are historical files and won't need updates.

**Comment by upkarlidder** [comment]
@joannhh any updates? Thank you!

**Comment by upkarlidder** [comment]
Created `assets` folder in the main repo. #67 

@joannhh and @sforsyth089 to add files here and link from the main readme.

**Comment by joannhh** [comment]
Still in process -- on target to upload the files by Friday.

**Comment by joannhh** [comment]
@upkarlidder I have some files ready to upload, but I don't appear to have file upload access to the new assets folder you created...

**Comment by upkarlidder** [comment]
Thank you @sforsyth089 and @joannhh for starting this work. Should we create a table in the [assets readme](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/blob/main/assets/README.md) explaining what each file is? That will help whoever comes to the assets folder for the first time. We should also add a link to the assets folder in the main project readme. I captured this idea in the original issue #54

**Comment by joannhh** [comment]
Upkar will open a new issue to accommodate the last comment.
