### ISSUE TITLE
Roles Based Entitlements and Access Requirements for Front and Back End

### ISSUE THREAD

**Issue by sforsyth089** [Call-for-Code-for-Racial-Justice/Open-Sentencing#75]
### Background on the problem the feature will solve/improved user experience
We want users to identify whether they are the office staff or public defender.  Then we will give access based on who is utilizing the tool.

We need roles in Excel.  Then across Columns - put entitlement (Read Only, Update Only, Etc).
Try two stories read & write, and read only.  Need at minimum.  Can see from there is there are other things.

### Describe the solution you'd like
First do the write up on access and who sees what for the Story
Then team members can do the programming part of it.
Break down incremental (maybe MS cohort can do some of it)

**Comment by sforsyth089** [comment]
Sorry for the delay, I should be finished today.

**Comment by sforsyth089** [comment]
[Open Sentencing User Roles.xlsx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/8064117/Open.Sentencing.User.Roles.xlsx)

**Comment by demilolu** [comment]
@btpull please see the user roles above for your flowchart work in the aggregator repo

**Comment by btpull** [comment]
@sforsyth089 I added a Roles - Entitlements tab and a Data Model tab
[Open.Sentencing.User.Roles.xlsx](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/files/8110671/Open.Sentencing.User.Roles.xlsx)
