### ISSUE TITLE
Current options for a client's race need to be verified

### ISSUE THREAD

**Issue by edelgrace** [Call-for-Code-for-Racial-Justice/Open-Sentencing#76]
### Background on the problem the feature will solve/improved user experience

In the aggregator, the following options for race are as below. Are these the correct values? For example, _White [Hispanic/Latino]_ is confusing.

![image](https://user-images.githubusercontent.com/3009729/153296262-b72ac11b-3b16-4dd4-a577-67995b02447a.png)

### Describe the solution you'd like

Get a clear list of the which race options are valid and how they should be displayed.

### Tasks 

- [ ] Get verified list of race options
- [ ] Change the aggregator API to return the correct list of race options

### Acceptance Criteria 

- The API should return the correct race options
- The front end should display the correct race options

**Comment by demilolu** [comment]
here's from the DOI:  https://www.doi.gov/pmb/eeo/directives/race-data

**Comment by joannhh** [comment]
Ok, reviewing the docs and will confirm.

**Comment by joannhh** [comment]
@demilolu Here's the background on Open Sentencing's use of the "race" field:

- The "Race" intake field represents the: "Race of defendant **reported by law enforcement** or **self-reported**" 

- Open Sentencing used the intake fields based on Cook County's dataset: ==> https://datacatalog.cookcountyil.gov/Courts/Sentencing/tg8v-tm6u/data

- **NOTE**: The Cook County dataset uses "White [Hispanic/Latino]"...; other counties, states, may use different race categories...

- Here's the Cook County dataset glossary which includes the definition/description of all fields: ==> https://www.cookcountystatesattorney.org/sites/default/files/files/documents/column_by_dataset_glossary_final_1.pdf

For the immediate purpose of the updates required for the project, the recommendation is to comply with the DOI standards previously mentioned (https://www.doi.gov/pmb/eeo/directives/race-data) which would fulfill the race identification and comparison intent of the project -- "Black" versus other races -- providing public defenders with insights and bias/disparity indicators per case. 

@sforsyth089

**Comment by demilolu** [comment]
thanks @joannhh , 

looking here at the DOI here: https://www.doi.gov/pmb/eeo/directives/race-data

and https://www.census.gov/quickfacts/fact/note/US/RHI625219

<img width="1055" alt="Screen Shot 2022-02-16 at 11 32 44 AM" src="https://user-images.githubusercontent.com/3202514/154311742-a886ed3c-1a46-4e37-9e1e-c4ed6e126144.png">

I'd recommend:


-     American Indian or Alaska Native
-     Asian 
-     Black or African American.
-     Hispanic or Latino. 
-     Native Hawaiian or Other Pacific Islander. 
-     White. 
-     Multi-racial


lastly to decide how to classify self-identified multi-racial 

Let's discuss.

cc @edelgrace

**Comment by edelgrace** [comment]
Thanks for looking into this @joannhh and @demilolu!

I think those options make more sense and should be doable to implement.

**Comment by sforsyth089** [comment]
Idea: Make display of races based on our best data sets right now.  Add a warning that is how we selected race/understanding that it is complex and may change over time. "If your race isn't represented, give us feedback (or something)"

**Comment by demilolu** [comment]
we discussed this more, I updated above accordingly @edelgrace @joannhh

**Comment by sethb4** [comment]
Pull request for changes to the backend aggregator are in https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/pull/53.

**Comment by joannhh** [comment]
Input provided and project completed; therefore closing out.
