### ISSUE TITLE
Add list of documents in the assets folder to the readme

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Open-Sentencing#77]
### Background on the problem the feature will solve/improved user experience
Thank you @sforsyth089 and @joannhh for finishing #54. The team decided to create a table or add a list in the [assets readme](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/blob/main/assets/README.md) describing the content of the folder. That will help whoever comes to the assets folder for the first time. We should also add a link to the assets folder in the main project readme. 

### Describe the solution you'd like
Add a list of files in the assets folder to the  [assets readme](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/blob/main/assets/README.md)

### Tasks 
- [ ] Add a list of files in the assets folder to the  [assets readme](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/blob/main/assets/README.md)

### Acceptance Criteria 
Add a list of files in the assets folder to the  [assets readme](https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing/blob/main/assets/README.md)

Assigning to @joannhh

**Comment by sforsyth089** [comment]
This is complete!
